repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
- repo: local
  hooks:
  - id: textlint
    name: textlint
    language: docker_image
    entry: textlint-container:0.1.1 textlint
    types: [asciidoc]
